server:
  port: 5002

spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.4:3307/getrand?serverTimezone=UTC
    username: mytest
    password: 1234

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    com.example.getrand_userservice: TRACE



#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka
#  instance:
#    # 2초동안 하트비트가 수신되지 않으면 서비스 등록을 해제
#    lease-expiration-duration-in-seconds: 2
#
#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
#        type:
#          descriptor:
#            sql: trace
